### ISSUE TITLE
Initialization failing frequently with version 2.1

### ISSUE THREAD

**Issue by matanvr** [magnetsystems/message-ios#67]
Initialization is failing very frequently for me -  when the magnet max init call gets executed. I get an error saying : "Read operation timed out" and that's basically about it. Any workaround for this? 

My code
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    // Override point for customization after application launch.
    // Configure MagnetMax
    NSString *configurationFile = [[NSBundle mainBundle] pathForResource:@"MagnetMax" ofType:@"plist"];
    id <MMConfiguration> configuration = [[MMPropertyListConfiguration alloc] initWithContentsOfFile:configurationFile];
    [MagnetMax configure:configuration];
...
}


View Controller:

-(void) viewWillAppear:(BOOL)animated {
    [super viewWillAppear:animated];
    
    SPTAuth *auth = [SPTAuth defaultInstance];
    if(![auth.session isValid]){
        [self performSegueWithIdentifier:@"ShowLogin" sender:nil];
        return;
    }
    [[NSNotificationCenter defaultCenter] addObserver:self
                                             selector:@selector(didReceiveMessage:)
                                                 name:MMXDidReceiveMessageNotification
                                               object:nil];
    //Show spinner
    [KVNProgress showWithStatus:@"Loading"
                         onView:self.view];
    [self initializeMessaging];
    
    
    [NSTimer scheduledTimerWithTimeInterval:0.5
                                     target:self
                                   selector:@selector(updateTimers:)
                                   userInfo:nil
                                    repeats:YES];
    
    
    
    
    
}

- (void) initializeMessaging {

    MMUser *user = [[MMUser alloc] init];
    user.userName = @"user1";
    user.password = @"user1";
    self.currentCredential = [NSURLCredential credentialWithUser:user.userName password:user.userName persistence:NSURLCredentialPersistencePermanent];
    
    [user register:^(MMUser *user) {
        [self logIn];
    } failure:^(NSError *error) {
        if (error.code == 409) {
            //Already registered
            [self logIn];
        }
    }];
}
- (void)logIn {
    if (self.currentCredential != nil) {
        
        [MMUser login:self.currentCredential success:^{
            [MagnetMax initModule:[MMX sharedInstance] success:^{
            
                [self connectToChannel];
                
            } failure:^(NSError * error) {
                 ****************FAILS HERE*****************
                 NSLog(@"initModule FAILURE error = %@", error.localizedDescription);

                
                
            }];
        } failure:^(NSError *error) {
            NSLog(@"Login error FAILURE!!!! = %@", error.localizedDescription);
            [KVNProgress dismiss];
        }];
    }
}

-(void) connectToChannel {
    [MMXChannel createWithName:self.channelId
                       summary:nil
                      isPublic:YES
            publishPermissions:MMXPublishPermissionsAnyone
                       success:^(MMXChannel *channel) {
                           NSLog(@"Successfully created channel");
                           //Different permissions level are MMXPublishPermissionsAnyone,MMXPublishPermissionsSubscribers,MMXPublishPermissionsOwnerOnly
                           self.channel = channel;
                           [self initializeMusic];
                       }
                       failure:^(NSError *error) {
                           // do something
                           if(error.code == 409){
                               [self joinExistingChannel];
                               
                           } else {
                               NSLog(@"Failed to connect channel");
                               [KVNProgress dismiss];
                           }
                       }];
}

- (void) joinExistingChannel {
    [MMXChannel channelForName:self.channelId
                      isPublic:YES
                       success:^(MMXChannel *channel) {
                           //Success
                           NSLog(@"Successfully joined channel");
                           self.channel = channel;
                           [self initializeMusic];
                           
                       } failure:^(NSError *error) {
                           //Failure
                       }];
}
```

**Comment by priteshshah1983** [comment]
Looking into it.

**Comment by priteshshah1983** [comment]
This issue should be resolved now.

**Comment by matanvr** [comment]
I am still experiencing this problem very frequently. Actually these failures unacceptable for the app I am building. Would you suggest deploying my own server with Magnet Message?

**Comment by priteshshah1983** [comment]
Are you still experiencing this issue? We are investigating. You should not need to deploy your own server.

**Comment by priteshshah1983** [comment]
Hi @matanvr,
Were you able to try it out again?

**Comment by matanvr** [comment]
Hi Pritesh,

Thanks for reaching out to me. Everything looks good right now. I really
appreciate it

Do you have any best practices for handling tokens from magnet?

Thanks,
Matan Vardi

**Comment by priteshshah1983** [comment]
Hi Matan,
I'm glad I could help! Are you talking about authentication tokens? Can you give me more details about what you are trying to do?

Thanks,
Pritesh.

**Comment by matanvr** [comment]
Hi Pritesh,

I was just wondering about whether or not I can have a user login once and
stay logged in even after the app is closed similarly to Facebook. For my
app I have no use case for the users. So I want to eliminate that logging
in part whenever the app starts up. Let me know if there is anything you
can recommend here.

Best,
Matan Vardi

**Comment by priteshshah1983** [comment]
Let me think about it a little bit more and evaluate if provide APIs to implement this easily. I'll get back to you.

**Comment by priteshshah1983** [comment]
Hi @matanvr,

Sorry for the late response! We currently offer an API to "remember" the current user:

```
/**
        Logs in as an user.
     
        - Parameters:
            - credential: A credential object containing the user's userName and password.
            - rememberMe: A boolean indicating if the user should stay logged in across app restarts.
            - success: A block object to be executed when the login finishes successfully. This block has no return value and takes no arguments.
            - failure: A block object to be executed when the login finishes with an error. This block has no return value and takes one argument: the error object.
     */
    static public func login(credential: NSURLCredential, rememberMe: Bool, success: (() -> Void)?, failure: ((error: NSError) -> Void)?)
```

But, we don't offer an API for you to check if the user is logged in on subsequent app launches. We are planning to add that in the next release (tentatively going out end of this week).

I hope that helps! And, let me know if you have further questions.
